### ISSUE TITLE
Tienes que poner ; al final de la línea.

### ISSUE THREAD

**Issue by a19sotean** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-a19caorda#1]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-a19caorda/blob/0b0394ff2e12894819c59f608d94ac4319db6507/Main.java#L10

**Comment by a19caorda** [comment]
Gracias! No me habia dado cuenta

**Comment by a19sotean** [comment]
De nada :)

**Comment by jaimerabasco** [comment]
Falta asignarte el commit y aplicar labels y milestone @a19caorda @dcxo 
Cierralo después

**Comment by a19caorda** [comment]
f29b1b0c14189194c433fffc511ef5cdfbeae754
